# Generated by Django 6.0.5 on 2026-05-19 17:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BClientPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 0), ("image", 1)]], {}),
                        },
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [("two_columns", 1)],
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 0)]], {}),
                        },
                    ),
                ),
                (
                    "big_supermarket",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                    ),
                ),
                (
                    "shops",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                    ),
                ),
                (
                    "horecd",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                    ),
                ),
                (
                    "fitness_club",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                    ),
                ),
                (
                    "cake_baker",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                    ),
                ),
                (
                    "down_banners",
                    wagtail.fields.StreamField(
                        [("supermarket", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 0), ("image", 1)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
