# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BClientPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="Верхний баннер",
                    ),
                ),
                ("page_title", models.CharField(max_length=255, verbose_name="Название страницы")),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [("two_columns", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {"label": "Левая колонка"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Правая колонка"}),
                            2: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 1)]], {}),
                        },
                        verbose_name="Описание",
                    ),
                ),
                (
                    "big_supermarket",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="Крупные супермаркеты",
                    ),
                ),
                (
                    "shops",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="Магазины",
                    ),
                ),
                (
                    "horecd",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="HoReCa",
                    ),
                ),
                (
                    "fitness_club",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="Фитнес клубы",
                    ),
                ),
                (
                    "cake_baker",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="Пекарни и кондитерские",
                    ),
                ),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("supermarket", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                        verbose_name="Нижние баннеры",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
