# Generated by Django 6.0.5 on 2026-05-29 23:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2bclientpage",
            name="big_supermarket_en",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Крупные супермаркеты",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="big_supermarket_ru",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Крупные супермаркеты",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="big_supermarket_uk",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Крупные супермаркеты",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="cake_baker_en",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Пекарни и кондитерские",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="cake_baker_ru",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Пекарни и кондитерские",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="cake_baker_uk",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Пекарни и кондитерские",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="description_en",
            field=wagtail.fields.StreamField(
                [("two_columns", 2)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Левая колонка"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Правая колонка"}),
                    2: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 1)]], {}),
                },
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="description_ru",
            field=wagtail.fields.StreamField(
                [("two_columns", 2)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Левая колонка"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Правая колонка"}),
                    2: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 1)]], {}),
                },
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="description_uk",
            field=wagtail.fields.StreamField(
                [("two_columns", 2)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Левая колонка"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Правая колонка"}),
                    2: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 1)]], {}),
                },
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="down_banner_en",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Нижние баннеры",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="down_banner_ru",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Нижние баннеры",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="down_banner_uk",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Нижние баннеры",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="fitness_club_en",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Фитнес клубы",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="fitness_club_ru",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Фитнес клубы",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="fitness_club_uk",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Фитнес клубы",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="horecd_en",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="HoReCa",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="horecd_ru",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="HoReCa",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="horecd_uk",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="HoReCa",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="page_title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Название страницы"),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="page_title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название страницы"),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="page_title_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Название страницы"),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="shops_en",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Магазины",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="shops_ru",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Магазины",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="shops_uk",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Магазины",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="upper_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="upper_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="b2bclientpage",
            name="upper_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
    ]
