# Generated by Django 6.0.5 on 2026-05-19 18:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_client", "0002_alter_b2bclientpage_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="b2bclientpage",
            old_name="name",
            new_name="page_title",
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="description",
            field=wagtail.fields.StreamField(
                [("two_columns", 1)],
                block_lookup={
                    0: ("wagtail.blocks.TextBlock", (), {}),
                    1: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 0)]], {}),
                },
            ),
        ),
    ]
