# Generated by Django 6.0.5 on 2026-05-19 18:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_client", "0003_rename_name_b2bclientpage_page_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b2bclientpage",
            name="description",
            field=wagtail.fields.StreamField(
                [("two_columns", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 0)]], {}),
                },
            ),
        ),
    ]
