# Generated by Django 6.0.5 on 2026-05-19 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_client", "0004_alter_b2bclientpage_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="b2bclientpage",
            old_name="down_banners",
            new_name="down_banner",
        ),
    ]
