# Generated by Django 6.0.5 on 2026-05-26 16:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b_client", "0005_rename_down_banners_b2bclientpage_down_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b2bclientpage",
            name="big_supermarket",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="Крупные супермаркеты",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="cake_baker",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="Пекарни и кондитерские",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="description",
            field=wagtail.fields.StreamField(
                [("two_columns", 2)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Левая колонка"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Правая колонка"}),
                    2: ("wagtail.blocks.StructBlock", [[("first_block", 0), ("second_block", 1)]], {}),
                },
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="down_banner",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="Нижние баннеры",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="fitness_club",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="Фитнес клубы",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="horecd",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="HoReCa",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="page_title",
            field=models.CharField(max_length=255, verbose_name="Название страницы"),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="shops",
            field=wagtail.fields.StreamField(
                [("supermarket", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="Магазины",
            ),
        ),
        migrations.AlterField(
            model_name="b2bclientpage",
            name="upper_banner",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                },
                verbose_name="Верхний баннер",
            ),
        ),
    ]
