# Generated by Django 6.0.5 on 2026-06-01 10:45

import django.db.models.deletion
import phonenumber_field.modelfields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccountSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("manager_name", models.CharField(max_length=255, verbose_name="Имя менеджера")),
                (
                    "manager_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, verbose_name="Номер телефона менеджера"
                    ),
                ),
                (
                    "banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("image", 2)]],
                                {"label": "Баннер"},
                            ),
                        },
                        verbose_name="Баннер",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
            },
        ),
    ]
