# Generated by Django 6.0.5 on 2026-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_useraccountsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discount",
            field=models.PositiveIntegerField(default=5, verbose_name="Скидка"),
        ),
    ]
