# Generated by Django 6.0.5 on 2026-05-26 16:46

import django.db.models.deletion
import phonenumber_field.modelfields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0014_alter_city_search_names"),
        ("user", "0003_termspage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individual",
            options={"verbose_name": "Физическое лицо", "verbose_name_plural": "Физические лица"},
        ),
        migrations.AlterModelOptions(
            name="legalentity",
            options={"verbose_name": "Юридическое лицо", "verbose_name_plural": "Юридические лица"},
        ),
        migrations.AlterField(
            model_name="individual",
            name="is_sole_proprietor",
            field=models.BooleanField(verbose_name="Является ФОП"),
        ),
        migrations.AlterField(
            model_name="individual",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="edrpou",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="ЕДРПОУ"),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="legal_address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Юр. адрес"),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="legal_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legal_city",
                to="cities_light.city",
                verbose_name="Юр. город",
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="legal_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_country",
                to="cities_light.country",
                verbose_name="Юр. страна",
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="legal_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legal_region",
                to="cities_light.region",
                verbose_name="Юр. регион",
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="postal_card",
            field=models.CharField(blank=True, max_length=5, verbose_name="Почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="reg_number",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="Рег. номер"),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="sp_address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес (СП)"),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="sp_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sp_city",
                to="cities_light.city",
                verbose_name="Город (СП)",
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="sp_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sp_country",
                to="cities_light.country",
                verbose_name="Страна (СП)",
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="sp_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sp_region",
                to="cities_light.region",
                verbose_name="Регион (СП)",
            ),
        ),
        migrations.AlterField(
            model_name="legalentity",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
        migrations.AlterField(
            model_name="termspage",
            name="content",
            field=wagtail.fields.RichTextField(verbose_name="Условия"),
        ),
        migrations.AlterField(
            model_name="termspage",
            name="page_title",
            field=models.CharField(max_length=255, verbose_name="Соглашение"),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="avatars", verbose_name="Аватар"),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="fullname",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.region",
                verbose_name="Регион",
            ),
        ),
    ]
