# Generated by Django 6.0.5 on 2026-06-05 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discount",
            field=models.PositiveIntegerField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)],
                verbose_name="Скидка",
            ),
        ),
    ]
