# Generated by Django 6.0.5 on 2026-05-27 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_individual_options_alter_legalentity_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
