[project]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = [
    {name = "snopy229",email = "jastcraft278@gmail.com"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "wagtail (>=7.3.1,<8.0.0)",
    "django-unfold[dashboard] (>=0.94.0,<0.95.0)",
    "celery (>=5.6.3,<6.0.0)",
    "redis (>=7.4.0,<8.0.0)",
    "django-environ (>=0.13.0,<0.14.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "django-vite (>=3.1.0,<4.0.0)",
    "wagtailgeowidget (>=9.1.0,<10.0.0)",
    "django-phonenumber-field (>=8.4.0,<9.0.0)",
    "django-cities-light (>=3.11,<4.0)",
    "phonenumbers (>=9.0.30,<10.0.0)",
    "wagtailmedia (>=0.17.2,<0.18.0)",
    "django-select2 (>=8.4.8,<9.0.0)",
    "django-ninja (>=1.6.2,<2.0.0)",
    "wagtail-modeltranslation (>=0.16.0,<0.17.0)",
    "django-trix (>=0.3.0,<0.4.0)",
    "django-ckeditor-5 (>=0.2.20,<0.3.0)",
    "transliterate (>=1.10.2,<2.0.0)",
    "django-middleware-global-request (>=0.3.6,<0.4.0)",
    "celery-types (>=0.26.0,<0.27.0)",
    "django-anymail[mailgun] (>=15.0,<16.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = ["migrations", "tests", ".venv"]
skips = ["B101"]

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings.dev"
[dependency-groups]
dev = [
    "pre-commit (>=4.6.0,<5.0.0)",
    "mypy (>=1.13.0,<1.20.0)",
    "django-stubs (>=6.0.3,<7.0.0)",
    "wagtail-stubs (>=7.3.0b1,<8.0.0)"
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["F403", "F405"]
