# Generated by Django 6.0.5 on 2026-05-24 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 0), ("video", 1), ("preview_image", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                ("page_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "gallery",
                    wagtail.fields.StreamField(
                        [("gallery", 0)], block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {})}
                    ),
                ),
                ("founder_fullname", models.CharField(max_length=255)),
                ("founder_information", models.TextField()),
                ("founder_quote", models.TextField()),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("banner", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 0), ("image", 1)]], {}),
                        },
                    ),
                ),
                (
                    "founder_photo",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wagtailimages.image"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
