# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 4)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                                {"label": "Баннер"},
                            ),
                        },
                        verbose_name="Верхний баннер",
                    ),
                ),
                ("page_title", models.CharField(max_length=255, verbose_name="Название страницы")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "gallery",
                    wagtail.fields.StreamField(
                        [("photo", 0), ("video", 3)],
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Фото"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("preview_image", 1), ("video", 2)]],
                                {"label": "Видео"},
                            ),
                        },
                        verbose_name="Галерея",
                    ),
                ),
                ("founder_fullname", models.CharField(max_length=255, verbose_name="Имя основателя")),
                ("founder_information", models.TextField(verbose_name="Информация об основателе")),
                ("founder_quote", models.TextField(verbose_name="Цитата основателя")),
                ("history", models.TextField(verbose_name="История")),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("banner", 4)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                                {"label": "Баннер"},
                            ),
                        },
                        verbose_name="Нижний баннер",
                    ),
                ),
                (
                    "founder_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtailimages.image",
                        verbose_name="Фото основателя",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
