# Generated by Django 6.0.5 on 2026-05-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0002_alter_productionpage_founder_photo"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionpage",
            name="founder_photo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wagtailimages.image"),
        ),
    ]
