# Generated by Django 6.0.5 on 2026-05-24 09:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0003_alter_productionpage_founder_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("photo", 0), ("video", 3)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 1), ("video", 2), ("preview_image", 0)]],
                        {},
                    ),
                },
            ),
        ),
    ]
