# Generated by Django 6.0.5 on 2026-05-24 11:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_alter_productionpage_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("photo", 0), ("video", 2)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    2: ("wagtail.blocks.StructBlock", [[("preview_image", 0), ("video", 1)]], {}),
                },
            ),
        ),
    ]
