# Generated by Django 6.0.5 on 2026-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0005_alter_productionpage_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionpage",
            name="history",
            field=models.TextField(default=123321),
            preserve_default=False,
        ),
    ]
