# Generated by Django 6.0.5 on 2026-05-24 12:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0006_productionpage_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionpage",
            name="down_banner",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 0), ("video", 1), ("preview_image", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
