# Generated by Django 6.0.5 on 2026-05-26 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0007_alter_productionpage_down_banner"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionpage",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="down_banner",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="founder_fullname",
            field=models.CharField(max_length=255, verbose_name="Имя основателя"),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="founder_information",
            field=models.TextField(verbose_name="Информация об основателе"),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="founder_photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wagtailimages.image", verbose_name="Фото основателя"
            ),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="founder_quote",
            field=models.TextField(verbose_name="Цитата основателя"),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("photo", 0), ("video", 3)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Фото"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.blocks.StructBlock", [[("preview_image", 1), ("video", 2)]], {"label": "Видео"}),
                },
                verbose_name="Галерея",
            ),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="history",
            field=models.TextField(verbose_name="История"),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="page_title",
            field=models.CharField(max_length=255, verbose_name="Название страницы"),
        ),
        migrations.AlterField(
            model_name="productionpage",
            name="upper_banner",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                verbose_name="Верхний баннер",
            ),
        ),
    ]
