# Generated by Django 6.0.5 on 2026-05-29 12:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0008_alter_productionpage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionpage",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="down_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="down_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="down_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_fullname_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя основателя"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_fullname_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя основателя"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_fullname_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя основателя"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_information_en",
            field=models.TextField(null=True, verbose_name="Информация об основателе"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_information_ru",
            field=models.TextField(null=True, verbose_name="Информация об основателе"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_information_uk",
            field=models.TextField(null=True, verbose_name="Информация об основателе"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_quote_en",
            field=models.TextField(null=True, verbose_name="Цитата основателя"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_quote_ru",
            field=models.TextField(null=True, verbose_name="Цитата основателя"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="founder_quote_uk",
            field=models.TextField(null=True, verbose_name="Цитата основателя"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="history_en",
            field=models.TextField(null=True, verbose_name="История"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="history_ru",
            field=models.TextField(null=True, verbose_name="История"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="history_uk",
            field=models.TextField(null=True, verbose_name="История"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="page_title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Название страницы"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="page_title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Название страницы"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="page_title_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Название страницы"),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="upper_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="upper_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productionpage",
            name="upper_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
    ]
