# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import trix.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, unique=True, verbose_name="Упаковка")),
            ],
        ),
        migrations.CreateModel(
            name="ProductsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {"label": "Баннер"}),
                        },
                        verbose_name="Верхний баннер",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(verbose_name="Описание")),
                (
                    "gallery",
                    wagtail.fields.StreamField(
                        [("gallery", 0)],
                        block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"})},
                        verbose_name="Галерея",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductTaste",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, unique=True, verbose_name="Название вкуса")),
            ],
        ),
        migrations.CreateModel(
            name="ProductWeight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, unique=True, verbose_name="Масса")),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetailPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("energy_value", models.IntegerField(verbose_name="Энергетическая ценность")),
                ("shelf_life", models.TextField(verbose_name="Срок годности")),
                ("description", trix.fields.TrixField(verbose_name="Описание")),
                ("description_photo", models.ImageField(upload_to="", verbose_name="/product/description")),
                ("package_description", trix.fields.TrixField(verbose_name="Упаковка")),
                ("package_photo", models.ImageField(upload_to="", verbose_name="/product/package")),
                ("payment", trix.fields.TrixField(verbose_name="Оплата")),
                ("payment_photo", models.ImageField(upload_to="", verbose_name="/product/payment")),
                ("delivery", trix.fields.TrixField(verbose_name="Доставка")),
                ("delivery_photo", models.ImageField(upload_to="", verbose_name="/product/delivery")),
                ("gallery", models.ManyToManyField(to="core.gallery", verbose_name="gallery")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productpackage",
                        verbose_name="Упаковка",
                    ),
                ),
                (
                    "taste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.producttaste", verbose_name="Вкус"
                    ),
                ),
                (
                    "mass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.productweight", verbose_name="Масса"
                    ),
                ),
            ],
        ),
    ]
