# Generated by Django 6.0.5 on 2026-05-25 13:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
