# Generated by Django 6.0.5 on 2026-05-29 23:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productspage",
            name="description_en",
            field=wagtail.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productspage",
            name="description_ru",
            field=wagtail.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productspage",
            name="description_uk",
            field=wagtail.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productspage",
            name="upper_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {"label": "Баннер"}),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="upper_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {"label": "Баннер"}),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="upper_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {"label": "Баннер"}),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
    ]
