# Generated by Django 6.0.5 on 2026-05-25 13:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productspage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspage",
            name="description",
            field=wagtail.fields.RichTextField(),
        ),
    ]
