# Generated by Django 6.0.5 on 2026-05-31 14:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productspage_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetailpage",
            name="delivery",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Доставка"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="package_description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Упаковка"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="payment",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Оплата"),
        ),
    ]
