# Generated by Django 6.0.5 on 2026-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productdetailpage_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpackage",
            name="title_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productpackage",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productpackage",
            name="title_uk",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="producttaste",
            name="title_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Название вкуса"),
        ),
        migrations.AddField(
            model_name="producttaste",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Название вкуса"),
        ),
        migrations.AddField(
            model_name="producttaste",
            name="title_uk",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Название вкуса"),
        ),
        migrations.AddField(
            model_name="productweight",
            name="title_en",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Масса"),
        ),
        migrations.AddField(
            model_name="productweight",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Масса"),
        ),
        migrations.AddField(
            model_name="productweight",
            name="title_uk",
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name="Масса"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="delivery",
            field=models.TextField(verbose_name="Доставка"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="package_description",
            field=models.TextField(verbose_name="Упаковка"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="payment",
            field=models.TextField(verbose_name="Оплата"),
        ),
    ]
