# Generated by Django 6.0.5 on 2026-05-25 19:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productspage_description"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "gallery",
                    wagtail.fields.StreamField(
                        [("images", 0)], block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {})}
                    ),
                ),
                ("nuts_type", models.CharField()),
                ("nuts_title", models.CharField(max_length=255)),
                ("compound", models.TextField()),
                ("mass", models.CharField(max_length=255)),
                ("energy_value", models.CharField(max_length=255)),
                ("shelf_life", models.CharField(max_length=255)),
                ("discount_value", models.IntegerField(blank=True, null=True)),
                ("article", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "blocks",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 1), ("image", 2)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
