# Generated by Django 6.0.5 on 2026-05-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productdetailpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="package",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="products.productpackage"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="taste",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="products.producttaste"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="article",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="nuts_type",
            field=models.CharField(max_length=255),
        ),
    ]
