# Generated by Django 6.0.5 on 2026-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productpackage_title_en_productpackage_title_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="cost",
            field=models.IntegerField(default=10, verbose_name="Цена"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="discount",
            field=models.IntegerField(blank=True, null=True, verbose_name="Скидка(грн)"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="delivery_photo",
            field=models.ImageField(upload_to="product/delivery", verbose_name="Доставка фото"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="description_photo",
            field=models.ImageField(upload_to="product/description", verbose_name="Описание фото"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="package_photo",
            field=models.ImageField(upload_to="product/package", verbose_name="Упаковка фото"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="payment_photo",
            field=models.ImageField(upload_to="product/payment", verbose_name="Оплата фото"),
        ),
    ]
