# Generated by Django 6.0.5 on 2026-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productdetailpage_cost_productdetailpage_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="title",
            field=models.CharField(default=12, max_length=255, verbose_name="Заголовок"),
            preserve_default=False,
        ),
    ]
