# Generated by Django 6.0.5 on 2026-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productdetailpage_package_productdetailpage_taste_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="cost",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
