# Generated by Django 6.0.5 on 2026-05-25 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productdetailpage_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productdetailpage",
            old_name="discount_value",
            new_name="discount",
        ),
    ]
