# Generated by Django 6.0.5 on 2026-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productdetailpage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name="Slug"),
        ),
    ]
