# Generated by Django 6.0.5 on 2026-05-25 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_rename_discount_value_productdetailpage_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWeight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="mass",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.productweight"),
        ),
    ]
