# Generated by Django 6.0.5 on 2026-05-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_productdetailpage_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="delivery_en",
            field=models.TextField(null=True, verbose_name="Доставка"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="delivery_ru",
            field=models.TextField(null=True, verbose_name="Доставка"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="delivery_uk",
            field=models.TextField(null=True, verbose_name="Доставка"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="package_description_en",
            field=models.TextField(null=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="package_description_ru",
            field=models.TextField(null=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="package_description_uk",
            field=models.TextField(null=True, verbose_name="Упаковка"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="payment_en",
            field=models.TextField(null=True, verbose_name="Оплата"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="payment_ru",
            field=models.TextField(null=True, verbose_name="Оплата"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="payment_uk",
            field=models.TextField(null=True, verbose_name="Оплата"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="shelf_life_en",
            field=models.TextField(null=True, verbose_name="Срок годности"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="shelf_life_ru",
            field=models.TextField(null=True, verbose_name="Срок годности"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="shelf_life_uk",
            field=models.TextField(null=True, verbose_name="Срок годности"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="title_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
