# Generated by Django 6.0.5 on 2026-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_productweight_productdetailpage_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpackage",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Упаковка"),
        ),
        migrations.AlterField(
            model_name="producttaste",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Название вкуса"),
        ),
        migrations.AlterField(
            model_name="productweight",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Масса"),
        ),
    ]
