# Generated by Django 6.0.5 on 2026-05-31 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_productdetailpage_delivery_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailpage",
            name="article",
            field=models.IntegerField(default=132, verbose_name="Артикул"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="compound",
            field=models.TextField(default="123134414", verbose_name="Состав"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="created_at",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="nuts_type",
            field=models.CharField(default="1231", max_length=255, verbose_name="Тип ореха"),
            preserve_default=False,
        ),
    ]
