# Generated by Django 6.0.5 on 2026-05-26 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_productpackage_title_alter_producttaste_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetailpage",
            name="article",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="blocks",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Раздел"},
                    ),
                },
                verbose_name="Разделы",
            ),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="compound",
            field=models.TextField(verbose_name="Состав"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="cost",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="discount",
            field=models.IntegerField(blank=True, null=True, verbose_name="Скидка (%)"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="energy_value",
            field=models.CharField(max_length=255, verbose_name="Энергетическая ценность"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("images", 0)],
                block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"})},
                verbose_name="Галерея",
            ),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="mass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.productweight", verbose_name="Масса"
            ),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="nuts_title",
            field=models.CharField(max_length=255, verbose_name="Название ореха"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="nuts_type",
            field=models.CharField(max_length=255, verbose_name="Вид ореха"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.productpackage", verbose_name="Упаковка"
            ),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="shelf_life",
            field=models.CharField(max_length=255, verbose_name="Срок годности"),
        ),
        migrations.AlterField(
            model_name="productdetailpage",
            name="taste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.producttaste", verbose_name="Вкус"
            ),
        ),
        migrations.AlterField(
            model_name="productspage",
            name="description",
            field=wagtail.fields.RichTextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="productspage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("gallery", 0)],
                block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"})},
                verbose_name="Галерея",
            ),
        ),
        migrations.AlterField(
            model_name="productspage",
            name="upper_banner",
            field=wagtail.fields.StreamField(
                [("banner", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {"label": "Баннер"}),
                },
                verbose_name="Верхний баннер",
            ),
        ),
    ]
