# Generated by Django 6.0.5 on 2026-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_productdetailpage_article_productdetailpage_compound_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetailpage",
            name="discount",
        ),
        migrations.AddField(
            model_name="productdetailpage",
            name="product_tags",
            field=models.CharField(
                choices=[("none", "Нету"), ("new", "Новый"), ("discount", "Скидка")],
                default="none",
                max_length=20,
                verbose_name="Теги",
            ),
        ),
    ]
