# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("image", 3), ("video", 6)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("image", 2)]],
                                {"label": "Изображение"},
                            ),
                            4: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 4), ("preview_image", 5)]],
                                {"label": "Видео"},
                            ),
                        },
                        verbose_name="Контент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галерея",
            },
        ),
        migrations.CreateModel(
            name="GalleryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "banner",
                    wagtail.fields.StreamField(
                        [("banner", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                                {"label": "Баннер"},
                            ),
                        },
                        verbose_name="Баннер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
