# Generated by Django 6.0.5 on 2026-05-19 10:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("image", 0), ("video", 3), ("card", 4)],
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            3: ("wagtail.blocks.StructBlock", [[("title", 1), ("description", 1), ("video", 2)]], {}),
                            4: ("wagtail.blocks.StructBlock", [[("title", 1), ("description", 1)]], {}),
                        },
                    ),
                ),
            ],
        ),
    ]
