# Generated by Django 6.0.5 on 2026-05-19 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Галерея"},
        ),
    ]
