# Generated by Django 6.0.5 on 2026-05-29 23:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="content_en",
            field=wagtail.fields.StreamField(
                [("image", 3), ("video", 6)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Изображение"},
                    ),
                    4: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 4), ("preview_image", 5)]],
                        {"label": "Видео"},
                    ),
                },
                null=True,
                verbose_name="Контент",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="content_ru",
            field=wagtail.fields.StreamField(
                [("image", 3), ("video", 6)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Изображение"},
                    ),
                    4: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 4), ("preview_image", 5)]],
                        {"label": "Видео"},
                    ),
                },
                null=True,
                verbose_name="Контент",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="content_uk",
            field=wagtail.fields.StreamField(
                [("image", 3), ("video", 6)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Изображение"},
                    ),
                    4: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 4), ("preview_image", 5)]],
                        {"label": "Видео"},
                    ),
                },
                null=True,
                verbose_name="Контент",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Баннер",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Баннер",
            ),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
                verbose_name="Баннер",
            ),
        ),
    ]
