# Generated by Django 6.0.5 on 2026-05-19 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_gallery_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="title",
        ),
    ]
