# Generated by Django 6.0.5 on 2026-05-19 13:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_gallerypage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="content",
            field=wagtail.fields.StreamField(
                [("image", 0), ("video", 3), ("card", 4)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("description", 1), ("video", 2), ("preview_image", 0)]],
                        {},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("title", 1), ("description", 1)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="gallerypage",
            name="banner",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 0), ("video", 1), ("preview_image", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
