# Generated by Django 6.0.5 on 2026-05-20 10:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_gallery_content_alter_gallerypage_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="content",
            field=wagtail.fields.StreamField(
                [("image", 2), ("video", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("description", 0), ("image", 1)]], {}),
                    3: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 0), ("video", 3), ("preview_image", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
