# Generated by Django 6.0.5 on 2026-06-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checkouts", "0002_orders_legalentityordercontact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cost", models.IntegerField(verbose_name="Стоимость")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Платеж принят"), ("waiting", "В ожидании оплаты")],
                        default="waiting",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="checkouts.orders"
                    ),
                ),
            ],
        ),
    ]
