# Generated by Django 6.0.5 on 2026-06-05 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0002_transaction_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="cost",
        ),
    ]
