# Generated by Django 6.0.5 on 2026-06-03 10:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0001_initial"),
        ("cities_light", "0014_alter_city_search_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("new_post", "Новая почта (по Украине оплата за счет Клиента)"),
                            ("courier", "Курьер по Одессе"),
                            ("pickup", "Самовывоз"),
                        ],
                        default="new_post",
                        max_length=20,
                        verbose_name="Способ доставки",
                    ),
                ),
                ("courier_address", models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Безналичный расчет"),
                            ("liqpay", "LiqPay / Приват24"),
                            ("cash", "Наличными при получении"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cart", models.ManyToManyField(related_name="checkouts", to="checkouts.cartitem")),
                (
                    "delivery_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cities_light.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "delivery_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.country",
                        verbose_name="Страна",
                    ),
                ),
                (
                    "delivery_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalEntityOrderContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company", models.CharField(blank=True, max_length=255, null=True, verbose_name="Компания")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Контактное лицо"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_entity_contact",
                        to="checkouts.orders",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndividualOrderContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fullname", models.CharField(max_length=255, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name="Телефон"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individual_contact",
                        to="checkouts.orders",
                    ),
                ),
            ],
        ),
    ]
