# Generated by Django 6.0.5 on 2026-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0003_alter_orders_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("new_post", "Новая почта (по Украине оплата за счет Клиента)"),
                    ("courier", "Курьер по Одессе"),
                    ("pickup", "Самовывоз"),
                ],
                default="new_post",
                max_length=20,
                verbose_name="Способ доставки",
            ),
        ),
    ]
