# Generated by Django 6.0.5 on 2026-06-03 12:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0005_thanksfororderpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="thanksfororderpage",
            name="banner_en",
            field=wagtail.fields.StreamField(
                [("photo", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thanksfororderpage",
            name="banner_ru",
            field=wagtail.fields.StreamField(
                [("photo", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thanksfororderpage",
            name="banner_uk",
            field=wagtail.fields.StreamField(
                [("photo", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Баннер"},
                    ),
                },
                null=True,
            ),
        ),
    ]
