# Generated by Django 6.0.5 on 2026-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0006_thanksfororderpage_banner_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_status",
            field=models.CharField(
                choices=[("waiting", "В ожидании"), ("sent", "Отправлено")],
                default="waiting",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
