# Generated by Django 6.0.5 on 2026-06-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0007_orders_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="cost",
            field=models.PositiveIntegerField(default=1090, verbose_name="Стоимость заказа"),
            preserve_default=False,
        ),
    ]
