# Generated by Django 6.0.5 on 2026-06-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkouts", "0008_orders_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="saved_cost",
            field=models.PositiveIntegerField(default=109, verbose_name="Цена на момент добавления"),
            preserve_default=False,
        ),
    ]
