# Generated by Django 6.0.5 on 2026-05-20 13:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAndDeliveryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("upper_banner", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {}),
                        },
                    ),
                ),
                (
                    "payment",
                    wagtail.fields.StreamField(
                        [("payment", 4)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 0)]], {}),
                            3: ("wagtail.blocks.StreamBlock", [[("Paragraph", 2)]], {}),
                            4: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 3), ("image", 1)]], {}),
                        },
                    ),
                ),
                (
                    "delivery",
                    wagtail.fields.StreamField(
                        [("delivery", 4)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 0)]], {}),
                            3: ("wagtail.blocks.StreamBlock", [[("Paragraph", 2)]], {}),
                            4: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 3), ("image", 1)]], {}),
                        },
                    ),
                ),
                (
                    "refund",
                    wagtail.fields.StreamField(
                        [("refund", 4)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 0)]], {}),
                            3: ("wagtail.blocks.StreamBlock", [[("Paragraph", 2)]], {}),
                            4: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 3), ("image", 1)]], {}),
                        },
                    ),
                ),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("down_banner", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 0), ("video", 1), ("preview_image", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
