# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAndDeliveryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("upper_banner", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("image", 1)]],
                                {"label": "Верхний баннер"},
                            ),
                        },
                        verbose_name="Верхний баннер",
                    ),
                ),
                (
                    "payment",
                    wagtail.fields.StreamField(
                        [("payment", 6)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Иконка"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            3: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 2)]], {}),
                            4: ("wagtail.blocks.StreamBlock", [[("Paragraph", 3)]], {"label": "Содержимое"}),
                            5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("content", 4), ("image", 5)]],
                                {"label": "Оплата"},
                            ),
                        },
                        verbose_name="Оплата",
                    ),
                ),
                (
                    "delivery",
                    wagtail.fields.StreamField(
                        [("delivery", 6)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Иконка"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            3: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 2)]], {}),
                            4: ("wagtail.blocks.StreamBlock", [[("Paragraph", 3)]], {"label": "Содержимое"}),
                            5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("content", 4), ("image", 5)]],
                                {"label": "Доставка"},
                            ),
                        },
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "refund",
                    wagtail.fields.StreamField(
                        [("refund", 6)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Иконка"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            3: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 2)]], {}),
                            4: ("wagtail.blocks.StreamBlock", [[("Paragraph", 3)]], {"label": "Содержимое"}),
                            5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("content", 4), ("image", 5)]],
                                {"label": "Возврат"},
                            ),
                        },
                        verbose_name="Возврат",
                    ),
                ),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("down_banner", 4)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                                {"label": "Нижний баннер"},
                            ),
                        },
                        verbose_name="Нижний баннер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
