# Generated by Django 6.0.5 on 2026-05-26 16:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_and_delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentanddeliverypage",
            name="delivery",
            field=wagtail.fields.StreamField(
                [("delivery", 6)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Иконка"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    3: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 2)]], {}),
                    4: ("wagtail.blocks.StreamBlock", [[("Paragraph", 3)]], {"label": "Содержимое"}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 4), ("image", 5)]],
                        {"label": "Доставка"},
                    ),
                },
                verbose_name="Доставка",
            ),
        ),
        migrations.AlterField(
            model_name="paymentanddeliverypage",
            name="down_banner",
            field=wagtail.fields.StreamField(
                [("down_banner", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Нижний баннер"},
                    ),
                },
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AlterField(
            model_name="paymentanddeliverypage",
            name="payment",
            field=wagtail.fields.StreamField(
                [("payment", 6)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Иконка"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    3: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 2)]], {}),
                    4: ("wagtail.blocks.StreamBlock", [[("Paragraph", 3)]], {"label": "Содержимое"}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 4), ("image", 5)]],
                        {"label": "Оплата"},
                    ),
                },
                verbose_name="Оплата",
            ),
        ),
        migrations.AlterField(
            model_name="paymentanddeliverypage",
            name="refund",
            field=wagtail.fields.StreamField(
                [("refund", 6)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Иконка"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    3: ("wagtail.blocks.StructBlock", [[("icon", 1), ("title", 0), ("description", 2)]], {}),
                    4: ("wagtail.blocks.StreamBlock", [[("Paragraph", 3)]], {"label": "Содержимое"}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 4), ("image", 5)]],
                        {"label": "Возврат"},
                    ),
                },
                verbose_name="Возврат",
            ),
        ),
        migrations.AlterField(
            model_name="paymentanddeliverypage",
            name="upper_banner",
            field=wagtail.fields.StreamField(
                [("upper_banner", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    2: ("wagtail.blocks.StructBlock", [[("title", 0), ("image", 1)]], {"label": "Верхний баннер"}),
                },
                verbose_name="Верхний баннер",
            ),
        ),
    ]
