# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsAndArticlesDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "preview",
                    wagtail.fields.StreamField(
                        [("image", 0), ("video", 3)],
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("preview_image", 1), ("video", 2)]],
                                {"label": "Видео"},
                            ),
                        },
                        verbose_name="Превью",
                    ),
                ),
                ("page_title", models.CharField(verbose_name="Название")),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [("text", 0), ("image", 1)],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст", "min_num": 1}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                        },
                        verbose_name="Информация",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsAndArticlesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_title", models.CharField(max_length=255, verbose_name="Заголовок страницы")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
