# Generated by Django 6.0.5 on 2026-05-23 12:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsAndArticlesDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "preview",
                    wagtail.fields.StreamField(
                        [("image", 0), ("video", 2)],
                        block_lookup={
                            0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("preview_image", 0), ("video", 1)]], {}),
                        },
                    ),
                ),
                ("page_title", models.CharField()),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [("text", 0), ("image", 1)],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {"min_num": 1}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                        },
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsAndArticlesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
