# Generated by Django 6.0.5 on 2026-05-26 16:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_and_articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsandarticlesdetailpage",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="newsandarticlesdetailpage",
            name="description",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст", "min_num": 1}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                },
                verbose_name="Информация",
            ),
        ),
        migrations.AlterField(
            model_name="newsandarticlesdetailpage",
            name="page_title",
            field=models.CharField(verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="newsandarticlesdetailpage",
            name="preview",
            field=wagtail.fields.StreamField(
                [("image", 0), ("video", 3)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.blocks.StructBlock", [[("preview_image", 1), ("video", 2)]], {"label": "Видео"}),
                },
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="newsandarticlespage",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="newsandarticlespage",
            name="page_title",
            field=models.CharField(max_length=255, verbose_name="Заголовок страницы"),
        ),
    ]
