# Generated by Django 6.0.5 on 2026-05-29 23:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_and_articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsandarticlesdetailpage",
            name="description_en",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст", "min_num": 1}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                },
                null=True,
                verbose_name="Информация",
            ),
        ),
        migrations.AddField(
            model_name="newsandarticlesdetailpage",
            name="description_ru",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст", "min_num": 1}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                },
                null=True,
                verbose_name="Информация",
            ),
        ),
        migrations.AddField(
            model_name="newsandarticlesdetailpage",
            name="description_uk",
            field=wagtail.fields.StreamField(
                [("text", 0), ("image", 1)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"label": "Текст", "min_num": 1}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                },
                null=True,
                verbose_name="Информация",
            ),
        ),
        migrations.AddField(
            model_name="newsandarticlesdetailpage",
            name="page_title_en",
            field=models.CharField(null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="newsandarticlesdetailpage",
            name="page_title_ru",
            field=models.CharField(null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="newsandarticlesdetailpage",
            name="page_title_uk",
            field=models.CharField(null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="newsandarticlespage",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="newsandarticlespage",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="newsandarticlespage",
            name="description_uk",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="newsandarticlespage",
            name="page_title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок страницы"),
        ),
        migrations.AddField(
            model_name="newsandarticlespage",
            name="page_title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок страницы"),
        ),
        migrations.AddField(
            model_name="newsandarticlespage",
            name="page_title_uk",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок страницы"),
        ),
    ]
