# Generated by Django 6.0.5 on 2026-05-19 19:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GardenInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tab_1",
                    wagtail.fields.StreamField(
                        [("block", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 1)]], {}),
                        },
                    ),
                ),
                (
                    "tab_2",
                    wagtail.fields.StreamField(
                        [("block", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 1)]], {}),
                        },
                    ),
                ),
                (
                    "tab_3",
                    wagtail.fields.StreamField(
                        [("block", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 1)]], {}),
                        },
                    ),
                ),
                (
                    "tab_4",
                    wagtail.fields.StreamField(
                        [("block", 2)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 1)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о саде",
            },
        ),
    ]
