# Generated by Django 6.0.5 on 2026-05-29 21:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("images", models.ImageField(upload_to="gallery/", verbose_name="Изображение")),
            ],
        ),
        migrations.CreateModel(
            name="GardenInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tab_1",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                        },
                        verbose_name="Вкладка 1",
                    ),
                ),
                (
                    "tab_2",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                        },
                        verbose_name="Вкладка 2",
                    ),
                ),
                (
                    "tab_3",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                        },
                        verbose_name="Вкладка 3",
                    ),
                ),
                (
                    "tab_4",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                        },
                        verbose_name="Вкладка 4",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о саде",
                "verbose_name_plural": "Информация о саде",
            },
        ),
    ]
