# Generated by Django 6.0.5 on 2026-05-26 16:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gardeninfo",
            options={"verbose_name": "Информация о саде", "verbose_name_plural": "Информация о саде"},
        ),
        migrations.AlterField(
            model_name="gardeninfo",
            name="tab_1",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                verbose_name="Вкладка 1",
            ),
        ),
        migrations.AlterField(
            model_name="gardeninfo",
            name="tab_2",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                verbose_name="Вкладка 2",
            ),
        ),
        migrations.AlterField(
            model_name="gardeninfo",
            name="tab_3",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                verbose_name="Вкладка 3",
            ),
        ),
        migrations.AlterField(
            model_name="gardeninfo",
            name="tab_4",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                verbose_name="Вкладка 4",
            ),
        ),
    ]
