# Generated by Django 6.0.5 on 2026-05-29 23:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_1_en",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 1",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_1_ru",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 1",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_1_uk",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 1",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_2_en",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 2",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_2_ru",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 2",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_2_uk",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 2",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_3_en",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 3",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_3_ru",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 3",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_3_uk",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 3",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_4_en",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 4",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_4_ru",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 4",
            ),
        ),
        migrations.AddField(
            model_name="gardeninfo",
            name="tab_4_uk",
            field=wagtail.fields.StreamField(
                [("block", 3)],
                block_lookup={
                    0: ("wagtail.blocks.IntegerBlock", (), {"label": "Метрика"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Единица измерения"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    3: ("wagtail.blocks.StructBlock", [[("metric", 0), ("unit", 1), ("title", 2)]], {}),
                },
                null=True,
                verbose_name="Вкладка 4",
            ),
        ),
    ]
