# Generated by Django 6.0.5 on 2026-05-18 07:05

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    wagtail.fields.StreamField(
                        [("phone_number", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.CharBlock", (), {"max_length": 20})},
                    ),
                ),
                ("viber_url", models.URLField(blank=True)),
                ("telegram_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("office_address", models.CharField(blank=True, max_length=255)),
                ("production_address", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=250)),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
