# Generated by Django 6.0.5 on 2026-05-29 21:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone_number",
                    wagtail.fields.StreamField(
                        [("phone_number", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.CharBlock", (), {"label": "Номер", "max_length": 20})},
                        verbose_name="Номера телефонов",
                    ),
                ),
                ("viber_url", models.URLField(blank=True, verbose_name="Viber")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                ("office_address", models.CharField(blank=True, max_length=255, verbose_name="Адрес офиса")),
                ("production_address", models.CharField(blank=True, max_length=255, verbose_name="Адрес производства")),
                ("location", models.CharField(blank=True, max_length=250, verbose_name="Местоположение")),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                                {"label": "Видео блок"},
                            ),
                        },
                        verbose_name="Верхний баннер",
                    ),
                ),
                ("products_title", models.CharField(max_length=20, verbose_name="Названия блока с продукцией")),
                ("products_description", models.TextField(verbose_name="Описание блока продукции")),
                (
                    "middle_banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("video", 1), ("preview_image", 2)]],
                                {"label": "Видео блок"},
                            ),
                        },
                        verbose_name="Баннер посередине",
                    ),
                ),
                ("benefits_title", models.CharField(max_length=30, verbose_name="Название блока с пользой")),
                ("benefits_description", models.TextField(verbose_name="Описание блока с пользой")),
                (
                    "walnut",
                    wagtail.fields.StreamField(
                        [("card", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("image", 2)]],
                                {"label": "Карточка"},
                            ),
                        },
                        verbose_name="Карточка грецкого ореха",
                    ),
                ),
                (
                    "hazelnut",
                    wagtail.fields.StreamField(
                        [("card", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("image", 2)]],
                                {"label": "Карточка"},
                            ),
                        },
                        verbose_name="Карточка лесного ореха",
                    ),
                ),
                (
                    "rose_hip",
                    wagtail.fields.StreamField(
                        [("card", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("image", 2)]],
                                {"label": "Карточка"},
                            ),
                        },
                        verbose_name="Карточка шиповника",
                    ),
                ),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("banner", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                            2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                            3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                                {"label": "Блок"},
                            ),
                        },
                        verbose_name="Нижний баннер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
