# Generated by Django 6.0.5 on 2026-05-26 13:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 0), ("video", 1), ("preview_image", 2)]],
                                {"label": "Видео блок"},
                            ),
                        },
                        verbose_name="Верхний баннер",
                    ),
                ),
                ("products_title", models.CharField(max_length=20, verbose_name="Названия блока с продукцией")),
                ("products_description", models.TextField(verbose_name="Описание блока продукции")),
                (
                    "middle_banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("video", 1), ("preview_image", 2)]],
                                {"label": "Видео блок"},
                            ),
                        },
                        verbose_name="Баннер посередине",
                    ),
                ),
                ("benefits_title", models.CharField(max_length=30, verbose_name="Название блока с пользой")),
                ("benefits_description", models.TextField(verbose_name="Описание блока с пользой")),
                (
                    "walnut",
                    wagtail.fields.StreamField(
                        [("card", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.TextBlock", (), {"label": "Карточка"})},
                        verbose_name="Карточка грецкого ореха",
                    ),
                ),
                (
                    "hazelnut",
                    wagtail.fields.StreamField(
                        [("card", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.TextBlock", (), {"label": "Карточка"})},
                        verbose_name="Карточка лесного ореха",
                    ),
                ),
                (
                    "rose_hip",
                    wagtail.fields.StreamField(
                        [("card", 0)],
                        blank=True,
                        block_lookup={0: ("wagtail.blocks.TextBlock", (), {"label": "Карточка"})},
                        verbose_name="Карточка шиповника",
                    ),
                ),
                (
                    "down_banner",
                    wagtail.fields.StreamField(
                        [("banner", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 0), ("video", 1), ("preview_image", 2)]],
                                {"label": "Блок"},
                            ),
                        },
                        verbose_name="Нижний баннер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="location",
            field=models.CharField(blank=True, max_length=250, verbose_name="Местоположение"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="office_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес офиса"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone_number",
            field=wagtail.fields.StreamField(
                [("phone_number", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.CharBlock", (), {"label": "Номер", "max_length": 20})},
                verbose_name="Номера телефонов",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="production_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес производства"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="telegram_url",
            field=models.URLField(blank=True, verbose_name="Telegram"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="viber_url",
            field=models.URLField(blank=True, verbose_name="Viber"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="whatsapp_url",
            field=models.URLField(blank=True, verbose_name="WhatsApp"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="YouTube"),
        ),
    ]
