# Generated by Django 6.0.5 on 2026-05-16 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
    ]
