# Generated by Django 6.0.5 on 2026-05-26 13:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_mainpage_alter_contacts_facebook_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpage",
            name="hazelnut",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                verbose_name="Карточка лесного ореха",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="rose_hip",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                verbose_name="Карточка шиповника",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="walnut",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                verbose_name="Карточка грецкого ореха",
            ),
        ),
    ]
