# Generated by Django 6.0.5 on 2026-05-26 16:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_mainpage_hazelnut_alter_mainpage_rose_hip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainpage",
            name="down_banner",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Блок"},
                    ),
                },
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="hazelnut",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                verbose_name="Карточка лесного ореха",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="middle_banner",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("video", 1), ("preview_image", 2)]],
                        {"label": "Видео блок"},
                    ),
                },
                verbose_name="Баннер посередине",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="rose_hip",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                verbose_name="Карточка шиповника",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="upper_banner",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Видео блок"},
                    ),
                },
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AlterField(
            model_name="mainpage",
            name="walnut",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                verbose_name="Карточка грецкого ореха",
            ),
        ),
    ]
