# Generated by Django 6.0.5 on 2026-05-29 12:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_mainpage_down_banner_alter_mainpage_hazelnut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="office_address_en",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес офиса"),
        ),
        migrations.AddField(
            model_name="contacts",
            name="office_address_ru",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес офиса"),
        ),
        migrations.AddField(
            model_name="contacts",
            name="office_address_uk",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес офиса"),
        ),
        migrations.AddField(
            model_name="contacts",
            name="production_address_en",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес производства"),
        ),
        migrations.AddField(
            model_name="contacts",
            name="production_address_ru",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес производства"),
        ),
        migrations.AddField(
            model_name="contacts",
            name="production_address_uk",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес производства"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="benefits_description_en",
            field=models.TextField(null=True, verbose_name="Описание блока с пользой"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="benefits_description_ru",
            field=models.TextField(null=True, verbose_name="Описание блока с пользой"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="benefits_description_uk",
            field=models.TextField(null=True, verbose_name="Описание блока с пользой"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="benefits_title_en",
            field=models.CharField(max_length=30, null=True, verbose_name="Название блока с пользой"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="benefits_title_ru",
            field=models.CharField(max_length=30, null=True, verbose_name="Название блока с пользой"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="benefits_title_uk",
            field=models.CharField(max_length=30, null=True, verbose_name="Название блока с пользой"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="down_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Блок"},
                    ),
                },
                null=True,
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="down_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Блок"},
                    ),
                },
                null=True,
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="down_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Блок"},
                    ),
                },
                null=True,
                verbose_name="Нижний баннер",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="hazelnut_en",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка лесного ореха",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="hazelnut_ru",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка лесного ореха",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="hazelnut_uk",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка лесного ореха",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="middle_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("video", 1), ("preview_image", 2)]],
                        {"label": "Видео блок"},
                    ),
                },
                null=True,
                verbose_name="Баннер посередине",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="middle_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("video", 1), ("preview_image", 2)]],
                        {"label": "Видео блок"},
                    ),
                },
                null=True,
                verbose_name="Баннер посередине",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="middle_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("video", 1), ("preview_image", 2)]],
                        {"label": "Видео блок"},
                    ),
                },
                null=True,
                verbose_name="Баннер посередине",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="products_description_en",
            field=models.TextField(null=True, verbose_name="Описание блока продукции"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="products_description_ru",
            field=models.TextField(null=True, verbose_name="Описание блока продукции"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="products_description_uk",
            field=models.TextField(null=True, verbose_name="Описание блока продукции"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="products_title_en",
            field=models.CharField(max_length=20, null=True, verbose_name="Названия блока с продукцией"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="products_title_ru",
            field=models.CharField(max_length=20, null=True, verbose_name="Названия блока с продукцией"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="products_title_uk",
            field=models.CharField(max_length=20, null=True, verbose_name="Названия блока с продукцией"),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="rose_hip_en",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка шиповника",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="rose_hip_ru",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка шиповника",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="rose_hip_uk",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка шиповника",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="upper_banner_en",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Видео блок"},
                    ),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="upper_banner_ru",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Видео блок"},
                    ),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="upper_banner_uk",
            field=wagtail.fields.StreamField(
                [("banner", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Описание"}),
                    2: ("wagtailmedia.blocks.VideoChooserBlock", (), {"label": "Видео"}),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Превью"}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("video", 2), ("preview_image", 3)]],
                        {"label": "Видео блок"},
                    ),
                },
                null=True,
                verbose_name="Верхний баннер",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="walnut_en",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка грецкого ореха",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="walnut_ru",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка грецкого ореха",
            ),
        ),
        migrations.AddField(
            model_name="mainpage",
            name="walnut_uk",
            field=wagtail.fields.StreamField(
                [("card", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Заголовок"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"label": "Описание"}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Изображение"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("image", 2)]],
                        {"label": "Карточка"},
                    ),
                },
                null=True,
                verbose_name="Карточка грецкого ореха",
            ),
        ),
    ]
